services:

  backend:
    image: ${BACKEND_IMAGE}
    pull_policy: always
    restart: always
    environment:
      RUN_SEED: "0"
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${RDS_ENDPOINT}:5432/fireaway_staging?sslmode=require
      ENVIRONMENT: staging
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      VALKEY_HOST: valkey
      VALKEY_PORT: 6379
      MINIO_ENDPOINT: minio:9000
      MINIO_SECURE: "false"
      MINIO_PUBLIC_ENDPOINT: staging.fireaway.site
      MINIO_PUBLIC_SECURE: "true"
      MINIO_ACCESS_KEY: ${MINIO_ROOT_USER}
      MINIO_SECRET_KEY: ${MINIO_ROOT_PASSWORD}
      MINIO_BUCKET: fire-reports
    networks:
      internal:
      edge:
        aliases: [backend-staging]
    

  frontend:
    image: ${FRONTEND_IMAGE}
    pull_policy: always
    networks:
      edge:
        aliases: [frontend-staging]

  valkey:
    image: valkey/valkey@sha256:3acc0687f2a2e1091fae6450d7842dd658c941338cf0a873ddd9e14b9e4ea4dd
    restart: always
    deploy:
      resources:
        limits:
          cpus: "0.05"
          memory: "128M"

  minio:
    image: minio/minio@sha256:14cea493d9a34af32f524e538b8346cf79f3321eff8e708c1e2960462bd8936e
    restart: always
    deploy: 
      resources:
        limits:
          cpus: "0.3"
          memory: 128M

networks:
  edge:
    external: true
    name: fireaway-edge